spring.datasource.url=jdbc:mysql://localhost:3306/jobapplication_db
spring.datasource.username=root
spring.datasource.password=mysqlkey@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080